### ISSUE TITLE
New Influence Framework v1

### ISSUE THREAD

**Issue by nateberkopec** [nateberkopec/antistasi#86]
* [ ] Remove any citysupportchange which is not a) military control or b) economic support
* [ ] Add a citysupportchange when one side has units in a zone and another does not
* [ ] Make sure AAF gets an influence bonus for roadblocks just like FIA does
* [ ] Reword the propaganda missions to be humanitarian support missions
* [ ] Rework powerplant as a form of economic support, rebalance
* [ ] Show military/economic influence scores to the player in a good way (not going back to base)
* [ ] Show all military/economic influence score CHANGES to the player

## Idea to consider

* Should fighting in a town decrease support for both sides? Any side?
