### ISSUE TITLE
New Mission Framework

### ISSUE THREAD

**Issue by nateberkopec** [nateberkopec/antistasi#87]
* [ ] #84 Missions should all use the same code framework
* [ ] There should only a small set of auto-assigned high-risk high-reward missions.
* [ ] #34 Mission Intel System - AOs have an intel level, higher intel levels generate more missions.
* [ ] Radio Tower System - Bugging radio towers should raise the intel level for an area.
* [ ] Economic Missions - create a set of fun missions for getting economic support in a town
* [ ] #33 Mission Firefight Revision - make missions fun by having different missions tailored towards generating different tactical situations
* [ ] Mission markers should be inaccurate, and get more accurate with intel level
